library(shiny)
library(shinythemes)
library(shinyBS)
library(DT)
library(plotly)
library(ggbeeswarm)
library(SummarizedExperiment)
library(vsn)
library(proDA)
library(limma)
library(DESeq2)
library(pheatmap)
library(ggplot2)
library(grid)
library(piano)
library(tidyr)
library(tibble)
library(dplyr)


#load("protCLL.RData")
load("data/ddsSub.RData")
load("data/screenData.RData")
load("data/pepCLL_lumos.RData")
load("data/patBack.RData")
patAnno <- patBack